"""artist -> ghost_albums_count; album + release_date,release_type

Revision ID: 22072aea588e
Revises: b0ecd67f7556
Create Date: 2026-04-19 12:14:57.357905

"""
from alembic import op

import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '22072aea588e'
down_revision = 'b0ecd67f7556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column("tolisten",sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column("tolisten",sa.Column('release_type', sa.String(), nullable=True))
    
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ghost_albums_count', sa.Integer(), nullable=True))


    
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('ghost_albums_count')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('release_type')
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
