"""new attributes for artist,album part2

Revision ID: 29c645eec193
Revises: 22072aea588e
Create Date: 2026-04-19 13:09:15.331508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c645eec193'
down_revision = '22072aea588e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('release_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('ghost_albums_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('ghost_albums_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('release_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
