"""nullable album columns

Revision ID: 2d9c0fc6c7fe
Revises: a481d7f5b396
Create Date: 2026-06-25 11:36:51.337038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9c0fc6c7fe'
down_revision = 'a481d7f5b396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('release_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ghost_songs_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('ghost_songs_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('release_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
