"""delete recommendation model

Revision ID: 3192197a8572
Revises: 92b8acd01483
Create Date: 2026-07-24 14:27:27.832697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3192197a8572'
down_revision = '92b8acd01483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reference_name', postgresql.ENUM('ALBUM', 'SONG', 'ARTIST', name='user_action_object_enum'), autoincrement=False, nullable=False),
    sa.Column('reference_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('recommendation_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendation_pkey'))
    )
    # ### end Alembic commands ###
