"""new enum value123

Revision ID: b0ecd67f7556
Revises: f6ef6d7e6319
Create Date: 2026-04-16 10:59:32.688624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ecd67f7556'
down_revision = 'f6ef6d7e6319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE action_name_enum ADD VALUE IF NOT EXISTS 'RATE_SONG'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
