"""init123

Revision ID: c74f30bb7f5f
Revises: cf7ce5c6c885
Create Date: 2026-04-06 18:00:43.568665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74f30bb7f5f'
down_revision = 'cf7ce5c6c885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('ghost_songs_count',
               existing_type=sa.INTEGER(),
               nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_genre_association', schema=None) as batch_op:
        batch_op.drop_constraint('uq_album_genre', type_='unique')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('ghost_songs_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
