"""init

Revision ID: cf7ce5c6c885
Revises: 
Create Date: 2026-04-06 11:13:46.904723

"""
from alembic import op
import sqlalchemy as sa
from app.model import Album
from sqlalchemy import select
from sqlalchemy.orm import Session
import deezer

# revision identifiers, used by Alembic.
revision = 'cf7ce5c6c885'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ghost_songs_count', sa.Integer(), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_genre_association', schema=None) as batch_op:
        batch_op.drop_constraint('uq_album_genre', type_='unique')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('ghost_songs_count')

    # ### end Alembic commands ###
