"""nullable song preview

Revision ID: d929e2bc3220
Revises: 6813a335f6d3
Create Date: 2026-07-09 09:49:53.916237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd929e2bc3220'
down_revision = '6813a335f6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('preview',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('preview',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
