"""+listened attribute in tolisten

Revision ID: e70b0bd0853d
Revises: d929e2bc3220
Create Date: 2026-07-11 15:43:51.104293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70b0bd0853d'
down_revision = 'd929e2bc3220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tolisten",sa.Column('listened', sa.Boolean(), nullable=True))
    op.execute("UPDATE tolisten SET listened = FALSE WHERE listened IS NULL")
    op.alter_column("tolisten",'listened',
            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tolisten', schema=None) as batch_op:
        batch_op.drop_column('listened')

    # ### end Alembic commands ###
