"""New model, changes to attributes

Revision ID: f6ef6d7e6319
Revises: c74f30bb7f5f
Create Date: 2026-04-15 17:36:55.419697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ef6d7e6319'
down_revision = 'c74f30bb7f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ALBUM_SHOW', 'ARTIST_SHOW', 'ADD_TO_LISTEN', 'RATE_ALBUM', name='action_name_enum'), nullable=False),
    sa.Column('reference_name', sa.Enum('ALBUM', 'SONG', 'ARTIST', name='user_action_object_enum'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_genre_association', schema=None) as batch_op:
        batch_op.drop_constraint('uq_album_genre', type_='unique')

    op.drop_table('action')
    # ### end Alembic commands ###
